import { Conversation, Message } from "@/lib/api/conversations";
import { marked } from "marked";
import hljs from "highlight.js";

/**
 * Generates HTML representation of a conversation for PDF export
 * @param conversation - The conversation to convert
 * @param messages - Array of messages to convert
 * @returns HTML string representation
 */
export function generateConversationHTML(
  conversation: Conversation,
  messages: Message[],
): string {
  const messageHTML = messages.map((msg) => generateMessageHTML(msg)).join("");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(conversation.title || "Conversation Export")}</title>
  <style>
    ${getStyles()}
  </style>
</head>
<body>
  <div class="container">
    <!-- Cover Page -->
    <div class="cover-page">
      <h1>${escapeHtml(conversation.title || "Untitled Conversation")}</h1>
      <div class="metadata">
        <p><strong>Mode:</strong> ${escapeHtml(conversation.mode)}</p>
        <p><strong>Started:</strong> ${formatDate(new Date(conversation.createdAt))}</p>
        <p><strong>Messages:</strong> ${messages.length}</p>
      </div>
      <p class="timestamp">Exported on ${new Date().toLocaleString()}</p>
    </div>

    <!-- Messages -->
    <div class="messages-section">
      <h2>Conversation</h2>
      ${messageHTML}
    </div>

    <!-- Footer -->
    <footer>
      <p>Generated by PALS CLI - Conversation Export</p>
    </footer>
  </div>
</body>
</html>`;

  return html;
}

/**
 * Generates HTML for a single message
 * @param message - The message to convert
 * @returns HTML string for the message
 */
function generateMessageHTML(message: Message): string {
  const isUser = message.role === "user";
  const role = isUser ? "User" : "Assistant";
  const time = new Date(message.createdAt).toLocaleTimeString();
  const html = marked.parse(message.content);

  return `
    <div class="message ${isUser ? "user-message" : "assistant-message"}">
      <div class="message-header">
        <span class="role">${role}</span>
        <span class="timestamp">${time}</span>
      </div>
      <div class="message-content">
        ${html}
      </div>
    </div>
  `;
}

/**
 * Get CSS styles for the exported HTML
 * @returns CSS string
 */
function getStyles(): string {
  return `
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      background: white;
    }

    .container {
      max-width: 8.5in;
      margin: 0 auto;
      padding: 20px;
      background: white;
    }

    h1 {
      font-size: 32px;
      margin-bottom: 20px;
      color: #1a1a1a;
      border-bottom: 3px solid #6366f1;
      padding-bottom: 15px;
    }

    h2 {
      font-size: 24px;
      margin-top: 30px;
      margin-bottom: 20px;
      color: #4b5563;
      page-break-after: avoid;
    }

    h3 {
      font-size: 18px;
      margin-top: 15px;
      margin-bottom: 10px;
      color: #4b5563;
    }

    p {
      margin-bottom: 12px;
    }

    /* Cover Page */
    .cover-page {
      text-align: center;
      padding: 60px 40px;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      margin-bottom: 40px;
      page-break-after: always;
      border-radius: 8px;
    }

    .cover-page h1 {
      color: white;
      border: none;
      padding: 0;
      font-size: 48px;
      margin-bottom: 40px;
    }

    .metadata {
      margin: 30px 0;
      font-size: 16px;
    }

    .metadata p {
      margin-bottom: 10px;
    }

    .timestamp {
      font-size: 14px;
      opacity: 0.9;
      margin-top: 20px;
    }

    /* Messages */
    .messages-section {
      margin-top: 30px;
    }

    .message {
      margin-bottom: 20px;
      padding: 12px;
      border-radius: 6px;
      page-break-inside: avoid;
    }

    .user-message {
      background-color: #e3f2fd;
      border-left: 4px solid #2196f3;
    }

    .assistant-message {
      background-color: #f5f5f5;
      border-left: 4px solid #666;
    }

    .message-header {
      display: flex;
      justify-content: space-between;
      margin-bottom: 8px;
      font-size: 12px;
      opacity: 0.7;
    }

    .role {
      font-weight: bold;
      text-transform: uppercase;
    }

    .message-content {
      font-size: 14px;
      line-height: 1.5;
    }

    .message-content code {
      background: #f0f0f0;
      padding: 2px 6px;
      border-radius: 3px;
      font-family: "Courier New", monospace;
      font-size: 13px;
    }

    .message-content pre {
      background: #2d2d2d;
      color: #f8f8f2;
      padding: 12px;
      border-radius: 6px;
      overflow-x: auto;
      margin: 10px 0;
      font-size: 12px;
      line-height: 1.4;
      page-break-inside: avoid;
    }

    .message-content pre code {
      background: none;
      padding: 0;
      color: inherit;
    }

    /* Syntax highlighting */
    .hljs {
      display: block;
      overflow-x: auto;
      background: inherit;
      color: inherit;
    }

    /* Links */
    a {
      color: #2196f3;
      text-decoration: none;
    }

    a:hover {
      text-decoration: underline;
    }

    /* Lists */
    ul, ol {
      margin-left: 20px;
      margin-bottom: 12px;
    }

    li {
      margin-bottom: 4px;
    }

    /* Blockquotes */
    blockquote {
      border-left: 4px solid #ddd;
      padding-left: 12px;
      margin: 12px 0;
      color: #666;
      font-style: italic;
    }

    /* Footer */
    footer {
      margin-top: 60px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      text-align: center;
      font-size: 12px;
      color: #999;
      page-break-before: avoid;
    }

    /* Print styles */
    @media print {
      body {
        margin: 0;
        padding: 0;
      }

      .container {
        padding: 0;
      }

      a {
        color: #0066cc;
      }

      .message {
        page-break-inside: avoid;
        display: block;
      }
    }
  `;
}

/**
 * Escape HTML special characters
 * @param text - The text to escape
 * @returns Escaped text safe for HTML
 */
function escapeHtml(text: string): string {
  const map: { [key: string]: string } = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (char) => map[char]);
}

/**
 * Formats a date in a human-readable way
 * @param date - The date to format
 * @returns Formatted date string
 */
function formatDate(date: Date): string {
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}
